{% set name = "easygdf" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/easygdf-{{ version }}.tar.gz
  sha256: 920bd033781870f085fdc7127b2d8bd48e7073df1fa5a90f5dfaca96b5de1b97

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.6
  run:
    - numpy
    - setuptools
    - python >=3.6

test:
  imports:
    - easygdf
    - easygdf.tests
  commands:
    - python -m unittest easygdf.tests

about:
  home: https://github.com/electronsandstuff/easygdf
  dev_url: https://github.com/electronsandstuff/easygdf
  summary: A python library to make working with GDF files a breeze.
  description: EasyGDF is a python library that simplifies the loading and saving of general datafile format (GDF) files used in the particle accelerator simulation code General Particle Tracer (GPT).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - electronsandstuff
